create table public.service_heartbeat_logs (
  id bigint generated by default as identity primary key,
  service_name text not null default 'object-echo-web',
  status text not null,
  latency_ms integer not null,
  environment text,
  deployment_url text,
  commit_sha text,
  error_message text,
  checked_at timestamptz not null default timezone('utc', now()),
  constraint service_heartbeat_logs_status_check
    check (status in ('healthy', 'unhealthy')),
  constraint service_heartbeat_logs_latency_check
    check (latency_ms >= 0)
);

create index service_heartbeat_logs_checked_at_idx
on public.service_heartbeat_logs (checked_at desc);

alter table public.service_heartbeat_logs enable row level security;

comment on table public.service_heartbeat_logs is
  'Server-only health check history written with the Supabase service role.';
